#!/usr/bin/env python3
from __future__ import annotations

import argparse
from html import escape as escape_xml
import json
from pathlib import Path
import re
import sys


DEFAULT_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = Path("localization/locales.json")
SOURCE_DIRECTORY = Path("localization/source")
MANIFEST_KEYS = {
    "schemaVersion",
    "sourceLocale",
    "localeSlots",
    "activeLocales",
    "plannedLocales",
    "androidStrings",
}
ACTIVE_LOCALE_KEYS = {
    "label",
    "androidQualifier",
    "readmeOutput",
    "changelogOutput",
    "humanReviewed",
}
ANDROID_STRING_KEYS = {"translatable", "nonTranslatable"}
LOCALE_PATTERN = re.compile(r"[a-z]{2,3}(?:-[A-Z][a-z]{3})?(?:-[A-Z]{2}|-[0-9]{3})?")
ANDROID_QUALIFIER_PATTERN = re.compile(r"values(?:-[a-z]{2,3}(?:-r[A-Z]{2})?)?")
ANDROID_KEY_PATTERN = re.compile(r"[a-z][a-z0-9_]*")
PLACEHOLDER_MARKERS = (
    "TODO_TRANSLATION",
    "TRANSLATION_PENDING",
    "MACHINE_TRANSLATION_PLACEHOLDER",
)


class LocalizedContentError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise LocalizedContentError(message)


def reject_duplicate_pairs(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        require(key not in result, f"Duplicate JSON key: {key}")
        result[key] = value
    return result


def load_json_strict(path: Path) -> object:
    require(path.is_file() and not path.is_symlink(), f"Missing regular source file: {path}")
    try:
        return json.loads(path.read_text("utf-8"), object_pairs_hook=reject_duplicate_pairs)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise LocalizedContentError(f"Invalid UTF-8 JSON: {path}") from error


def exact_object(value: object, keys: set[str], label: str) -> dict[str, object]:
    require(isinstance(value, dict), f"{label} must be an object")
    require(set(value) == keys, f"{label} key inventory drift: {sorted(value)}")
    return value


def string_list(value: object, label: str) -> list[str]:
    require(isinstance(value, list), f"{label} must be an array")
    require(all(isinstance(item, str) and item for item in value), f"{label} contains an invalid item")
    result = list(value)
    require(len(result) == len(set(result)), f"{label} contains duplicates")
    return result


def safe_relative_path(root: Path, value: object, label: str) -> Path:
    require(isinstance(value, str) and bool(value), f"{label} must be a non-empty path")
    relative = Path(value)
    require(not relative.is_absolute() and ".." not in relative.parts, f"{label} escapes the repository")
    resolved = (root / relative).resolve()
    require(resolved == root or root in resolved.parents, f"{label} escapes the repository")
    return relative


def read_markdown(path: Path, locale: str, kind: str) -> str:
    require(path.is_file() and not path.is_symlink(), f"Missing regular {locale} {kind} source")
    try:
        text = path.read_text("utf-8")
    except UnicodeDecodeError as error:
        raise LocalizedContentError(f"Invalid UTF-8 Markdown: {path}") from error
    require("\r" not in text, f"{path} must use LF line endings")
    text = text.rstrip("\n") + "\n"
    require(text.startswith("# "), f"{path} must start with one level-one heading")
    for marker in PLACEHOLDER_MARKERS:
        require(
            marker.lower() not in text.lower(),
            f"Translation placeholder is forbidden in {path}: {marker}",
        )
    if locale == "zh-CN":
        require(
            len(re.findall(r"[\u4e00-\u9fff]", text)) >= (200 if kind == "README" else 20),
            f"{path} does not contain reviewed Simplified Chinese content",
        )
    return text


def render_markdown(source: str, locale: str, kind: str, navigation: str) -> str:
    source_name = f"{kind}.md"
    marker = (
        f"<!-- Generated from localization/source/{locale}/{source_name} by "
        "tools/generate_localized_content.py. Do not edit this file directly. -->"
    )
    return f"{marker}\n\n{navigation}\n\n{source}"


def load_android_strings(
    path: Path,
    expected_keys: list[str],
    locale: str,
) -> dict[str, str]:
    value = load_json_strict(path)
    require(isinstance(value, dict), f"{locale} Android strings must be an object")
    require(list(value) == expected_keys, f"{locale} Android string key/order drift")
    result: dict[str, str] = {}
    for key, item in value.items():
        require(isinstance(item, str) and item and item == item.strip(), f"Invalid {locale} string: {key}")
        require("\n" not in item and "\r" not in item, f"Multiline Android string is forbidden: {key}")
        for marker in PLACEHOLDER_MARKERS:
            require(
                marker.lower() not in item.lower(),
                f"Translation placeholder is forbidden in {path}: {marker}",
            )
        result[key] = item
    if locale == "zh-CN":
        require(
            any(re.search(r"[\u4e00-\u9fff]", item) for item in result.values()),
            "Simplified Chinese Android strings contain no Chinese text",
        )
    return result


def android_escape(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return escape_xml(escaped, quote=False)


def render_android_strings(
    locale: str,
    values: dict[str, str],
    non_translatable: set[str],
) -> str:
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        (
            f"<!-- Generated from localization/source/{locale}/strings.json by "
            "tools/generate_localized_content.py. -->"
        ),
        "<resources>",
    ]
    for key, value in values.items():
        attribute = ' translatable="false"' if key in non_translatable else ""
        lines.append(f'    <string name="{key}"{attribute}>{android_escape(value)}</string>')
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def generated_output_inventory(root: Path) -> set[Path]:
    inventory = set(path.relative_to(root) for path in root.glob("README*.md"))
    inventory.update(path.relative_to(root) for path in root.glob("CHANGELOG*.md"))
    resource_root = root / "app/src/main/res"
    if resource_root.is_dir():
        inventory.update(
            path.relative_to(root)
            for path in resource_root.glob("values*/strings.xml")
        )
    return inventory


def build_artifacts(root: Path) -> tuple[dict[Path, str], int, int]:
    root = root.resolve()
    manifest = exact_object(load_json_strict(root / MANIFEST_PATH), MANIFEST_KEYS, "Locale manifest")
    require(type(manifest["schemaVersion"]) is int and manifest["schemaVersion"] == 1, "Locale schema drift")

    source_locale = manifest["sourceLocale"]
    require(isinstance(source_locale, str), "sourceLocale must be a string")
    slots = string_list(manifest["localeSlots"], "localeSlots")
    planned = string_list(manifest["plannedLocales"], "plannedLocales")
    active = manifest["activeLocales"]
    require(isinstance(active, dict) and active, "activeLocales must be a non-empty object")
    active_names = list(active)

    require(len(slots) == 10, "The localization workflow must retain exactly ten locale slots")
    require(all(LOCALE_PATTERN.fullmatch(locale) for locale in slots), "Invalid BCP-47 locale slot")
    require(source_locale == "en" and slots[0] == source_locale, "English must remain the source locale")
    require(active_names[:2] == ["en", "zh-CN"], "English and zh-CN must be the first active locales")
    require(set(active_names).isdisjoint(planned), "A locale cannot be both active and planned")
    require(slots == active_names + planned, "localeSlots must equal active locales followed by planned locales")

    android_spec = exact_object(manifest["androidStrings"], ANDROID_STRING_KEYS, "androidStrings")
    translatable = string_list(android_spec["translatable"], "translatable Android strings")
    non_translatable = string_list(android_spec["nonTranslatable"], "non-translatable Android strings")
    all_string_keys = translatable + non_translatable
    require(all(ANDROID_KEY_PATTERN.fullmatch(key) for key in all_string_keys), "Invalid Android string key")
    require(len(all_string_keys) == len(set(all_string_keys)), "Android string inventories overlap")

    source_root = root / SOURCE_DIRECTORY
    require(source_root.is_dir() and not source_root.is_symlink(), "Missing regular localization source directory")
    actual_source_locales = sorted(path.name for path in source_root.iterdir() if path.is_dir())
    require(
        actual_source_locales == sorted(active_names),
        "Only active locales may have source directories; planned locales must remain source-free",
    )

    qualifiers: set[str] = set()
    output_paths: set[Path] = set()
    locale_configs: dict[
        str,
        tuple[dict[str, object], str, Path, Path, Path],
    ] = {}
    for locale, raw_config in active.items():
        require(locale in slots, f"Active locale is not declared in localeSlots: {locale}")
        config = exact_object(raw_config, ACTIVE_LOCALE_KEYS, f"Active locale {locale}")
        require(config["humanReviewed"] is True, f"Active locale must be human-reviewed: {locale}")
        label = config["label"]
        require(
            isinstance(label, str)
            and re.fullmatch(r"[^\[\]\r\n]{1,40}", label) is not None,
            f"Invalid locale label: {locale}",
        )
        qualifier = config["androidQualifier"]
        require(
            isinstance(qualifier, str)
            and ANDROID_QUALIFIER_PATTERN.fullmatch(qualifier) is not None,
            f"Invalid Android qualifier for {locale}",
        )
        require(qualifier not in qualifiers, f"Duplicate Android qualifier: {qualifier}")
        qualifiers.add(qualifier)

        readme_output = safe_relative_path(root, config["readmeOutput"], f"{locale} README output")
        changelog_output = safe_relative_path(root, config["changelogOutput"], f"{locale} changelog output")
        require(
            readme_output.parent == Path(".") and readme_output.name.startswith("README"),
            f"Unexpected README output for {locale}",
        )
        require(
            changelog_output.parent == Path(".") and changelog_output.name.startswith("CHANGELOG"),
            f"Unexpected changelog output for {locale}",
        )
        resource_output = Path(f"app/src/main/res/{qualifier}/strings.xml")
        locale_outputs = {readme_output, changelog_output, resource_output}
        require(len(locale_outputs) == 3, f"Duplicate generated output for {locale}")
        require(output_paths.isdisjoint(locale_outputs), "Duplicate generated output")
        output_paths.update(locale_outputs)
        locale_configs[locale] = (
            config,
            qualifier,
            readme_output,
            changelog_output,
            resource_output,
        )

    readme_navigation = " | ".join(
        f"[{config['label']}]({readme_output.as_posix()})"
        for config, _, readme_output, _, _ in locale_configs.values()
    )
    changelog_navigation = " | ".join(
        f"[{config['label']}]({changelog_output.as_posix()})"
        for config, _, _, changelog_output, _ in locale_configs.values()
    )

    artifacts: dict[Path, str] = {}
    source_fingerprints: dict[
        str,
        tuple[tuple[int, ...], int, tuple[str, ...], tuple[str, ...], tuple[str, ...]],
    ] = {}
    for locale, (
        config,
        qualifier,
        readme_output,
        changelog_output,
        resource_output,
    ) in locale_configs.items():
        locale_source = source_root / locale
        require(
            locale_source.is_dir() and not locale_source.is_symlink(),
            f"Locale source directory must be regular: {locale}",
        )
        require(
            {path.name for path in locale_source.iterdir()} == {"README.md", "CHANGELOG.md", "strings.json"},
            f"Locale source inventory drift: {locale}",
        )
        readme_source = read_markdown(locale_source / "README.md", locale, "README")
        changelog_source = read_markdown(locale_source / "CHANGELOG.md", locale, "CHANGELOG")
        for kind, source in (("README", readme_source), ("CHANGELOG", changelog_source)):
            fingerprint = (
                tuple(
                    len(match.group(1))
                    for line in source.splitlines()
                    if (match := re.fullmatch(r"(#{1,6}) .+", line)) is not None
                ),
                sum(line.startswith("```") for line in source.splitlines()),
                tuple(sorted(set(re.findall(r"\b(?:[0-9a-f]{40}|[0-9a-f]{64})\b", source)))),
                tuple(sorted(set(re.findall(r"https://[^\s`)]+", source)))),
                tuple(sorted(set(re.findall(r"\]\(([^)\s]+)\)", source)))),
            )
            require(
                fingerprint[0] and fingerprint[1] % 2 == 0,
                f"Invalid Markdown structure: {locale} {kind}",
            )
            if locale == source_locale:
                source_fingerprints[kind] = fingerprint
            else:
                require(
                    fingerprint == source_fingerprints[kind],
                    f"Translated Markdown structure or protected literal drift: {locale} {kind}",
                )
        artifacts[readme_output] = render_markdown(
            readme_source,
            locale,
            "README",
            readme_navigation,
        )
        artifacts[changelog_output] = render_markdown(
            changelog_source,
            locale,
            "CHANGELOG",
            changelog_navigation,
        )

        expected_locale_keys = all_string_keys if locale == source_locale else translatable
        string_values = load_android_strings(locale_source / "strings.json", expected_locale_keys, locale)
        artifacts[resource_output] = render_android_strings(locale, string_values, set(non_translatable))

    return artifacts, len(active_names), len(planned)


def write_or_check(root: Path, check: bool) -> tuple[int, int, int]:
    artifacts, active_count, planned_count = build_artifacts(root)
    actual_outputs = generated_output_inventory(root)
    expected_outputs = set(artifacts)
    if check:
        require(
            actual_outputs == expected_outputs,
            "Generated output inventory drift: "
            f"expected={sorted(map(str, expected_outputs))}, actual={sorted(map(str, actual_outputs))}",
        )
    else:
        require(
            actual_outputs <= expected_outputs,
            "Unexpected generated outputs must be removed before generation: "
            f"{sorted(map(str, actual_outputs - expected_outputs))}",
        )
    for relative, expected in artifacts.items():
        destination = root / relative
        if check:
            require(
                destination.is_file() and not destination.is_symlink(),
                f"Missing regular generated output: {relative}",
            )
            actual = destination.read_text("utf-8")
            require(actual == expected, f"Generated content drift: {relative}")
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            with destination.open("w", encoding="utf-8", newline="\n") as stream:
                stream.write(expected)
    return active_count, planned_count, len(artifacts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate reviewed localized repository content")
    parser.add_argument("--check", action="store_true", help="Fail if generated files have drifted")
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    try:
        root = args.root.resolve()
        active, planned, artifacts = write_or_check(root, args.check)
    except (LocalizedContentError, OSError) as error:
        print(f"LOCALIZED_CONTENT_ERROR {error}", file=sys.stderr)
        return 1
    mode = "check" if args.check else "write"
    print(
        "LOCALIZED_CONTENT_OK "
        f"active={active} planned={planned} artifacts={artifacts} mode={mode}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
